# Generated by Django 3.2.6 on 2022-01-03 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('make', models.TextField()),
                ('brand', models.TextField()),
                ('year', models.IntegerField(default=2000)),
                ('capacity', models.IntegerField()),
                ('condition', models.IntegerField()),
                ('approved', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', related_query_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cars',
                'managed': True,
            },
        ),
    ]
